export default interface TubeFormat {
  asr: number;
  filesize: number;
  filesizeCap: string | number;
  format_id: any;
  format_note: any;
  source_preference: any;
  fps: number;
  audio_channels: number;
  height: number;
  quality: any;
  has_drm: any;
  tbr: number;
  url: any;
  width: number;
  language: any;
  language_preference: any;
  preference: any;
  ext: any;
  vcodec: any;
  acodec: any;
  dynamic_range: any;
  container: any;
  downloader_options: any;
  protocol: any;
  resolution: any;
  aspect_ratio: any;
  http_headers: any;
  audio_ext: any;
  video_ext: any;
  vbr: number;
  abr: number;
  format: any;
}
